### ISSUE TITLE
Cannot detect wow

### ISSUE THREAD

**Issue by Primordial808** [leoaviana/WoWmapperX#2]
For whatever reason i cannot get it to detect wow, Im using ascension and the controls seem to work on there but it doesnt detect it. I try adding it into the json and then it wont start? Confused on what im doing wrong.

**Comment by leoaviana** [comment]
If it doesn't detect wow, it is probably because you're using their launcher which requires administrator privileges, try opening with administrator privileges. also update your WoWmapperX version, 1.1.0 is available now and in a few minutes a new ConsolePortLK version will be drafted with some workarounds for Ascension.

Closing this as it's not an issue.
